// Actual Chromium flow/DOM/responsive checks; data fixture is synthetic, no DB.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {spawn} = require('node:child_process');
const {spawnSync} = require('node:child_process');
const {once} = require('node:events');
const {createHash} = require('node:crypto');
const readline = require('node:readline');
const {chromium} = require(process.env.CANCA_PLAYWRIGHT_MODULE || 'playwright');

(async () => {
  const fixture = spawn(process.env.CANCA_BROWSER_PYTHON || 'python', [path.join(__dirname, 'operator_web_browser_fixture.py')], {stdio:['ignore','pipe','pipe']});
  const lines = readline.createInterface({input:fixture.stdout});
  let browser;
  const readyTimeout = setTimeout(() => fixture.kill('SIGINT'), 20000);
  try {
    const [line] = await Promise.race([once(lines, 'line'), once(fixture, 'exit').then(() => { throw new Error('browser fixture exited before ready'); })]);
    clearTimeout(readyTimeout);
    const url = JSON.parse(line).url;
    browser = await chromium.launch({headless:true});
    const artifacts = process.env.CANCA_BROWSER_OUTPUT || path.join(__dirname, '../.web-ci-artifacts');
    fs.mkdirSync(artifacts, {recursive:true});
    for (const width of [1280, 390]) {
      const context = await browser.newContext({viewport:{width, height:900}});
      const page = await context.newPage(); const errors = [], external = [], reportRequests = [];
      page.on('pageerror', () => errors.push('pageerror'));
      page.on('request', request => {
        const target = new URL(request.url());
        if (target.origin !== new URL(url).origin) external.push('external-request');
        if (/\/api\/v1\/assessments\/[^/]+\/report$/.test(target.pathname)) reportRequests.push(target.pathname);
      });
      await page.goto(url); await page.getByRole('heading', {name:'Entrar na Cancã'}).waitFor();
      await page.screenshot({path:path.join(artifacts, `login-${width}.png`), fullPage:true});
      await page.getByLabel('Usuário', {exact:true}).fill('browser-reader');
      await page.getByLabel('Senha', {exact:true}).fill('Synthetic browser CI passphrase 01!');
      await page.getByRole('button', {name:'Entrar', exact:true}).click();
      await page.getByText('4 assessment(s) permitido(s). Selecione e clique em Consultar.', {exact:true}).waitFor();
      assert.equal(await page.locator('#password').inputValue(), '');
      assert.deepEqual(await page.locator('#assessment-selector option').evaluateAll(options=>options.map(o=>o.value)),
        ['', 'LAB-001', 'LAB-EMPTY', 'LAB-MANY', 'LAB-MISSING']);
      assert.equal(reportRequests.length,0);
      await page.getByLabel('Assessments permitidos', {exact:true}).selectOption('LAB-MISSING');
      assert.equal(await page.locator('#assessment').inputValue(),'LAB-MISSING');
      assert.equal(reportRequests.length,0);
      await page.getByRole('button', {name:'Consultar', exact:true}).click();
      await page.getByText('Assessment não encontrado.', {exact:true}).waitFor();
      assert.equal(await page.locator('#report-panel').isVisible(),false);
      await page.getByLabel('Assessments permitidos', {exact:true}).selectOption('LAB-001');
      await page.screenshot({path:path.join(artifacts, `assessments-${width}.png`), fullPage:true});
      await page.getByLabel('Avaliações por página', {exact:true}).selectOption('1');
      await page.getByRole('button', {name:'Consultar', exact:true}).click();
      await page.getByText('Página 1 · 1 avaliação(ões)', {exact:true}).waitFor();
      assert.equal(await page.locator('#asset-count').innerText(), '1');
      assert.equal(await page.locator('#evaluation-count').innerText(), '4');
      assert.equal(await page.locator('#finding-count').innerText(), '2');
      assert.ok((await page.locator('#evaluations').innerText()).includes('<img src=x'));
      assert.equal(await page.locator('#evaluations img').count(), 0);
      assert.equal(await page.evaluate(() => window.cancaInjected), undefined);
      const firstFocus = await page.evaluate(() => document.activeElement.id);
      assert.equal(firstFocus, 'report-title');
      for (let number=2; number<=4; number++) {
        await page.getByRole('button', {name:'Próxima página', exact:true}).click();
        await page.getByText(`Página ${number} · 1 avaliação(ões)`, {exact:true}).waitFor();
      }
      assert.equal(await page.locator('#next-button').isDisabled(), true);
      await page.getByRole('button', {name:'Primeira página', exact:true}).click();
      await page.getByText('Página 1 · 1 avaliação(ões)', {exact:true}).waitFor();
      const previewResponseEvent = page.waitForResponse(response=>new URL(response.url()).pathname === '/api/v1/assessments/LAB-001/report/executive');
      await page.getByRole('button', {name:'Ver resumo executivo', exact:true}).click();
      const previewResponse = await previewResponseEvent;
      await page.getByText('Resumo executivo carregado.', {exact:true}).waitFor();
      const previewBytes = await previewResponse.body(), previewHeaders = previewResponse.headers();
      assert.equal(previewResponse.status(),200);
      assert.equal(previewHeaders['content-type'],'application/json; charset=utf-8');
      assert.equal(Number(previewHeaders['content-length']),previewBytes.length);
      assert.equal(previewHeaders['x-canca-report-scope-sha256'],'a'.repeat(64));
      assert.equal(previewHeaders['x-canca-executive-preview-sha256'],createHash('sha256').update(previewBytes).digest('hex'));
      const previewDoc=JSON.parse(previewBytes);
      assert.equal(previewDoc.coverage.evaluation_count,4); assert.equal(previewDoc.recorded_finding_occurrences,2);
      assert.equal(previewDoc.consistency.terminal_empty_page_verified,true);
      assert.equal(previewDoc.semantics.occurrence_references_included,false);
      assert.equal(await page.locator('#preview-groups article').count(),2);
      assert.equal(await page.locator('#preview-groups img').count(),0);
      assert.ok((await page.locator('#preview-groups').innerText()).includes('<img src=x'));
      assert.match(await page.locator('#preview-coverage').innerText(),/^4 avaliações/);
      assert.match(await page.locator('#preview-outcomes').innerText(),/sem finding: 2/);
      assert.equal(await page.evaluate(()=>document.activeElement.id),'preview-title');
      await page.locator('#preview-groups details').first().locator('summary').click();
      assert.ok((await page.locator('#preview-groups details pre').first().innerText()).includes('c'.repeat(64)));
      assert.equal(await page.evaluate(()=>window.cancaInjected),undefined);
      fs.writeFileSync(path.join(artifacts,`preview-${width}.json`),previewBytes);
      await page.screenshot({path:path.join(artifacts, `preview-${width}.png`),fullPage:true});
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
      await page.getByRole('button', {name:'Ocultar resumo',exact:true}).click();
      assert.equal(await page.locator('#preview-panel').isVisible(),false);
      assert.equal(await page.locator('#preview-groups article').count(),0);
      assert.equal(await page.locator('#report-panel').isVisible(),true);
      const downloadEvent = page.waitForEvent('download');
      await page.getByRole('button', {name:'Baixar relatório completo (ZIP)', exact:true}).click();
      const download = await downloadEvent;
      assert.equal(download.suggestedFilename(),'canca-LAB-001-report.zip');
      const archive = path.join(artifacts,`report-${width}.zip`);
      await download.saveAs(archive);
      await page.getByText('Relatório completo preparado para download.',{exact:true}).waitFor();
      assert.equal(await page.evaluate(()=>document.activeElement.id),'download-button');
      const verify=spawnSync(process.env.CANCA_BROWSER_PYTHON || 'python',[
        path.join(__dirname,'../docs/validation/VERIFY_OPERATOR_WEB_EXPORT_v0.6.13.py'),
        '--archive',archive,'--assessment-id','LAB-001','--evaluation-count','4','--finding-count','2'],{encoding:'utf8'});
      assert.equal(verify.status,0,verify.stdout+verify.stderr);
      assert.equal(JSON.parse(verify.stdout).files_verified,4);
      const executiveEvent = page.waitForEvent('download');
      await page.getByRole('button', {name:'Baixar relatório executivo (ZIP)', exact:true}).click();
      const executive = await executiveEvent;
      assert.equal(executive.suggestedFilename(),'canca-LAB-001-executive.zip');
      const executiveArchive = path.join(artifacts,`executive-${width}.zip`);
      await executive.saveAs(executiveArchive);
      await page.getByText('Relatório executivo preparado para download.',{exact:true}).waitFor();
      assert.equal(await page.evaluate(()=>document.activeElement.id),'executive-download-button');
      const verifyExecutive=spawnSync(process.env.CANCA_BROWSER_PYTHON || 'python',[
        path.join(__dirname,'../docs/validation/VERIFY_OPERATOR_WEB_EXECUTIVE_v0.6.15.py'),
        '--archive',executiveArchive,'--assessment-id','LAB-001','--evaluation-count','4',
        '--finding-count','2','--recommendation-group-count','2'],{encoding:'utf8'});
      assert.equal(verifyExecutive.status,0,verifyExecutive.stdout+verifyExecutive.stderr);
      assert.equal(JSON.parse(verifyExecutive.stdout).files_verified,4);
      await page.screenshot({path:path.join(artifacts, `report-${width}.png`), fullPage:true});
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
      assert.equal(await page.evaluate(() => localStorage.length + sessionStorage.length), 0);
      assert.deepEqual(await context.cookies(), []);
      await page.getByLabel('Assessments permitidos', {exact:true}).selectOption('LAB-MANY');
      await page.getByRole('button', {name:'Consultar',exact:true}).click();
      await page.getByText('Página 1 · 1 avaliação(ões)', {exact:true}).waitFor();
      await page.getByRole('button', {name:'Ver resumo executivo',exact:true}).click();
      await page.getByText('Grupos 1–10 de 12', {exact:true}).waitFor();
      assert.equal(await page.locator('#preview-groups article').count(),10);
      await page.getByRole('button', {name:'Próximas recomendações',exact:true}).click();
      await page.getByText('Grupos 11–12 de 12', {exact:true}).waitFor();
      assert.equal(await page.locator('#preview-groups article').count(),2);
      assert.equal(await page.locator('#preview-next-button').isDisabled(),true);
      await page.getByRole('button', {name:'Primeiras recomendações',exact:true}).click();
      await page.getByText('Grupos 1–10 de 12', {exact:true}).waitFor();
      await page.getByRole('button', {name:'Próxima página',exact:true}).click();
      await page.getByText('Página 2 · 1 avaliação(ões)', {exact:true}).waitFor();
      assert.equal(await page.locator('#preview-panel').isVisible(),true);
      assert.equal(await page.locator('#preview-groups article').count(),10);
      await page.getByLabel('Assessments permitidos', {exact:true}).selectOption('LAB-EMPTY');
      assert.equal(await page.locator('#preview-panel').isVisible(),false);
      assert.equal(await page.locator('#preview-groups article').count(),0);
      await page.getByRole('button', {name:'Consultar',exact:true}).click();
      await page.getByText('Página 1 · 0 avaliação(ões)', {exact:true}).waitFor();
      await page.getByRole('button', {name:'Ver resumo executivo',exact:true}).click();
      await page.getByText('0 grupos registrados', {exact:true}).waitFor();
      assert.equal(await page.locator('#preview-groups article').count(),0);
      assert.equal(await page.locator('#preview-empty').isVisible(),true);
      assert.match(await page.locator('#preview-empty').innerText(),/não comprova segurança/);
      assert.match(await page.locator('#preview-coverage').innerText(),/^0 avaliações/);
      assert.equal(await page.evaluate(() => localStorage.length + sessionStorage.length),0);
      assert.deepEqual(await context.cookies(),[]);
      const beforeSelection=reportRequests.length;
      await page.getByLabel('Assessments permitidos', {exact:true}).selectOption('LAB-MISSING');
      assert.equal(await page.locator('#report-panel').isVisible(),false);
      assert.equal(await page.locator('#download-button').isDisabled(),true);
      assert.equal(reportRequests.length,beforeSelection);
      await page.getByLabel('ID do assessment', {exact:true}).fill('LAB-OTHER');
      await page.getByRole('button', {name:'Consultar', exact:true}).click();
      await page.getByText('Sua conta não possui acesso a este assessment.', {exact:true}).waitFor();
      assert.equal(await page.locator('#report-panel').isVisible(), false);
      await page.getByRole('button', {name:'Sair', exact:true}).click();
      await page.getByRole('heading', {name:'Entrar na Cancã'}).waitFor();
      assert.equal(await page.locator('#assessment-selector option').count(),1);
      assert.equal(await page.locator('#preview-groups article').count(),0);
      await page.getByLabel('Usuário', {exact:true}).fill('other-reader');
      await page.getByLabel('Senha', {exact:true}).fill('Synthetic browser CI passphrase 01!');
      await page.getByRole('button', {name:'Entrar', exact:true}).click();
      await page.getByText('1 assessment(s) permitido(s). Selecione e clique em Consultar.', {exact:true}).waitFor();
      assert.deepEqual(await page.locator('#assessment-selector option').evaluateAll(options=>options.map(o=>o.value)), ['', 'PRIVATE-OTHER']);
      await page.getByRole('button', {name:'Atualizar lista', exact:true}).click();
      await page.getByText('1 assessment(s) permitido(s). Selecione e clique em Consultar.', {exact:true}).waitFor();
      await page.getByRole('button', {name:'Sair', exact:true}).click();
      await page.getByLabel('Usuário', {exact:true}).fill('empty-reader');
      await page.getByLabel('Senha', {exact:true}).fill('Synthetic browser CI passphrase 01!');
      await page.getByRole('button', {name:'Entrar', exact:true}).click();
      await page.getByText('Sua conta não possui assessments permitidos.', {exact:true}).waitFor();
      assert.equal(await page.locator('#assessment-selector').isDisabled(),true);
      assert.equal(await page.locator('#assessment').isDisabled(),false);
      await page.getByRole('button', {name:'Sair', exact:true}).click();
      await page.reload(); await page.getByRole('heading', {name:'Entrar na Cancã'}).waitFor();
      assert.equal(await page.locator('#workspace').isVisible(), false);
      assert.deepEqual(errors, []); assert.deepEqual(external, []);
      await context.close();
    }
    console.log('OPERATOR WEB BROWSER PASS — Chromium desktop/mobile, executive preview/hash/empty/12-group pagination, isolated grants, unchanged technical and executive ZIPs');
  } finally {
    clearTimeout(readyTimeout); if (browser) await browser.close(); lines.close();
    if (fixture.exitCode === null) { const exit = once(fixture, 'exit'); fixture.kill('SIGINT'); await exit; }
  }
})().catch(error => { console.error('OPERATOR WEB BROWSER FAILED', error); process.exitCode=1; });
